//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c://Users//marci//Desktop//Structural Language//AntlrCSharp//ParserRules.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="ParserRulesParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IParserRulesVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserRulesParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] ParserRulesParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserRulesParser.definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefinition([NotNull] ParserRulesParser.DefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserRulesParser.structDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructDefinition([NotNull] ParserRulesParser.StructDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserRulesParser.enumerableDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumerableDefinition([NotNull] ParserRulesParser.EnumerableDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserRulesParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction([NotNull] ParserRulesParser.FunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserRulesParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclaration([NotNull] ParserRulesParser.VariableDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserRulesParser.arrayDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayDeclaration([NotNull] ParserRulesParser.ArrayDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserRulesParser.arrayAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayAssignment([NotNull] ParserRulesParser.ArrayAssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserRulesParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] ParserRulesParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserRulesParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] ParserRulesParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserRulesParser.expressionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionStatement([NotNull] ParserRulesParser.ExpressionStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserRulesParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStatement([NotNull] ParserRulesParser.WhileStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserRulesParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForStatement([NotNull] ParserRulesParser.ForStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserRulesParser.doWhileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoWhileStatement([NotNull] ParserRulesParser.DoWhileStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserRulesParser.switchStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchStatement([NotNull] ParserRulesParser.SwitchStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserRulesParser.case_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCase_([NotNull] ParserRulesParser.Case_Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserRulesParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStatement([NotNull] ParserRulesParser.ReturnStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserRulesParser.breakStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBreakStatement([NotNull] ParserRulesParser.BreakStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserRulesParser.continueStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContinueStatement([NotNull] ParserRulesParser.ContinueStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserRulesParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] ParserRulesParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserRulesParser.ternary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTernary([NotNull] ParserRulesParser.TernaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserRulesParser.binary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinary([NotNull] ParserRulesParser.BinaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserRulesParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary([NotNull] ParserRulesParser.PrimaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserRulesParser.unary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnary([NotNull] ParserRulesParser.UnaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserRulesParser.grouping"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGrouping([NotNull] ParserRulesParser.GroupingContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserRulesParser.arrayAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayAccess([NotNull] ParserRulesParser.ArrayAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserRulesParser.call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCall([NotNull] ParserRulesParser.CallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserRulesParser.typeCast"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeCast([NotNull] ParserRulesParser.TypeCastContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserRulesParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] ParserRulesParser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParserRulesParser.fieldAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldAccess([NotNull] ParserRulesParser.FieldAccessContext context);
}
