//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c://Users//marci//Desktop//Structural Language//AntlrCSharp//ParserRules.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IParserRulesListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class ParserRulesBaseListener : IParserRulesListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] ParserRulesParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] ParserRulesParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefinition([NotNull] ParserRulesParser.DefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefinition([NotNull] ParserRulesParser.DefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.structDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructDefinition([NotNull] ParserRulesParser.StructDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.structDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructDefinition([NotNull] ParserRulesParser.StructDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.enumerableDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumerableDefinition([NotNull] ParserRulesParser.EnumerableDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.enumerableDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumerableDefinition([NotNull] ParserRulesParser.EnumerableDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction([NotNull] ParserRulesParser.FunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction([NotNull] ParserRulesParser.FunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.variableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclaration([NotNull] ParserRulesParser.VariableDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.variableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclaration([NotNull] ParserRulesParser.VariableDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.arrayDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayDeclaration([NotNull] ParserRulesParser.ArrayDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.arrayDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayDeclaration([NotNull] ParserRulesParser.ArrayDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.arrayAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayAssignment([NotNull] ParserRulesParser.ArrayAssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.arrayAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayAssignment([NotNull] ParserRulesParser.ArrayAssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] ParserRulesParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] ParserRulesParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] ParserRulesParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] ParserRulesParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.expressionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionStatement([NotNull] ParserRulesParser.ExpressionStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.expressionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionStatement([NotNull] ParserRulesParser.ExpressionStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.whileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileStatement([NotNull] ParserRulesParser.WhileStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.whileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileStatement([NotNull] ParserRulesParser.WhileStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.forStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForStatement([NotNull] ParserRulesParser.ForStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.forStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForStatement([NotNull] ParserRulesParser.ForStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.doWhileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDoWhileStatement([NotNull] ParserRulesParser.DoWhileStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.doWhileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDoWhileStatement([NotNull] ParserRulesParser.DoWhileStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.switchStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchStatement([NotNull] ParserRulesParser.SwitchStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.switchStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchStatement([NotNull] ParserRulesParser.SwitchStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.case_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCase_([NotNull] ParserRulesParser.Case_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.case_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCase_([NotNull] ParserRulesParser.Case_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnStatement([NotNull] ParserRulesParser.ReturnStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnStatement([NotNull] ParserRulesParser.ReturnStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.breakStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBreakStatement([NotNull] ParserRulesParser.BreakStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.breakStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBreakStatement([NotNull] ParserRulesParser.BreakStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.continueStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContinueStatement([NotNull] ParserRulesParser.ContinueStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.continueStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContinueStatement([NotNull] ParserRulesParser.ContinueStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] ParserRulesParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] ParserRulesParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.ternary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTernary([NotNull] ParserRulesParser.TernaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.ternary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTernary([NotNull] ParserRulesParser.TernaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.binary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinary([NotNull] ParserRulesParser.BinaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.binary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinary([NotNull] ParserRulesParser.BinaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimary([NotNull] ParserRulesParser.PrimaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimary([NotNull] ParserRulesParser.PrimaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.unary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnary([NotNull] ParserRulesParser.UnaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.unary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnary([NotNull] ParserRulesParser.UnaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.grouping"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGrouping([NotNull] ParserRulesParser.GroupingContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.grouping"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGrouping([NotNull] ParserRulesParser.GroupingContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.arrayAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayAccess([NotNull] ParserRulesParser.ArrayAccessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.arrayAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayAccess([NotNull] ParserRulesParser.ArrayAccessContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCall([NotNull] ParserRulesParser.CallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCall([NotNull] ParserRulesParser.CallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.typeCast"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeCast([NotNull] ParserRulesParser.TypeCastContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.typeCast"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeCast([NotNull] ParserRulesParser.TypeCastContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] ParserRulesParser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] ParserRulesParser.AssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.fieldAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldAccess([NotNull] ParserRulesParser.FieldAccessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.fieldAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldAccess([NotNull] ParserRulesParser.FieldAccessContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
