//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c://Users//marci//Desktop//Structural Language//AntlrCSharp//ParserRules.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ParserRulesParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IParserRulesListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] ParserRulesParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] ParserRulesParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.ternary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTernary([NotNull] ParserRulesParser.TernaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.ternary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTernary([NotNull] ParserRulesParser.TernaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.binary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinary([NotNull] ParserRulesParser.BinaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.binary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinary([NotNull] ParserRulesParser.BinaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimary([NotNull] ParserRulesParser.PrimaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimary([NotNull] ParserRulesParser.PrimaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] ParserRulesParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] ParserRulesParser.ValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.binaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinaryOp([NotNull] ParserRulesParser.BinaryOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.binaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinaryOp([NotNull] ParserRulesParser.BinaryOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber([NotNull] ParserRulesParser.NumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber([NotNull] ParserRulesParser.NumberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.true"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTrue([NotNull] ParserRulesParser.TrueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.true"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTrue([NotNull] ParserRulesParser.TrueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.false"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFalse([NotNull] ParserRulesParser.FalseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.false"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFalse([NotNull] ParserRulesParser.FalseContext context);
}
