//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c://Users//marci//Desktop//Structural Language//AntlrCSharp//ParserRules.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IParserRulesListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class ParserRulesBaseListener : IParserRulesListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] ParserRulesParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] ParserRulesParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.ternary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTernary([NotNull] ParserRulesParser.TernaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.ternary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTernary([NotNull] ParserRulesParser.TernaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.binary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinary([NotNull] ParserRulesParser.BinaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.binary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinary([NotNull] ParserRulesParser.BinaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimary([NotNull] ParserRulesParser.PrimaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimary([NotNull] ParserRulesParser.PrimaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue([NotNull] ParserRulesParser.ValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue([NotNull] ParserRulesParser.ValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.binaryOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinaryOp([NotNull] ParserRulesParser.BinaryOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.binaryOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinaryOp([NotNull] ParserRulesParser.BinaryOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber([NotNull] ParserRulesParser.NumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber([NotNull] ParserRulesParser.NumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.true"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTrue([NotNull] ParserRulesParser.TrueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.true"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTrue([NotNull] ParserRulesParser.TrueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParserRulesParser.false"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFalse([NotNull] ParserRulesParser.FalseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParserRulesParser.false"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFalse([NotNull] ParserRulesParser.FalseContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
